name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test-stable:
    name: Build and test, Rust-stable
    runs-on: ubuntu-latest
    steps:
      # Get a checkout and rust toolchain.
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      # Build and test
      - run: cargo +stable build
      - run: cargo +stable test
      - run: cargo +stable bench --no-run
